### ISSUE TITLE
Option to set speed as an enumerated value (1-7)

### ISSUE THREAD

**Issue by dr** [oogje/homebridge-i6-bigAssFans#12]
The Big Ass Fans app sets the speed of the Haiku L as a value in the range 1-7.  (I don't have a different model and am unsure whether this behaviour applies to all consumer models.)

Would it be possible to provide a configuration option that allows the fan to have these seven speeds listed explicitly so that I can say, "Hey Siri, set the living room fan speed to 3" instead of using a percentage?  I'm lazy and don't always want to do the maths :)

I am very happy to help test this feature (or any new release) on our fan.

Thank you for your consideration.

**Comment by oogje** [comment]
I'd also like to be able to set the fan speed from 1 to 7 but I don't know how to sensibly implement that. 

The HomeKit interface requires the speed be set as a percentage.  I can imagine doing some hackery like a "Siri mode" switch, that when activated causes the plugin to interpret 3% as 43%, 5% as 71%, etc.

When you would say "Hey Siri, set the living room fan speed to 3", Siri would respond "OK, I've set the living room fan speed to 3%" but the plugin would actually set the speed to 3 out of 7. 

When in this mode, the graphical interface is also going to be messy because the labels will indicate percentage and the entire speed adjustment range will be compressed into the bottom 7% of the slider.
However, you could turn the Siri mode switch "on" before you use Siri and "off" after. 

If I were able to implement this hack, I wouldn't document it.  It would be our secret.  Does this sound like something you'd want to pursue?
