### ISSUE TITLE
Option for showFanDirectionSwitch

### ISSUE THREAD

**Issue by bschuchert** [oogje/homebridge-i6-bigAssFans#13]
**Is your feature request related to a problem? Please describe:**
As stated in the documentation, Big Ass Fans discourages reversing speed. Having the option available in the Home app opens up the possibility that a family member will inadvertently toggle that at some point.

**Describe the solution you'd like:**
I'd like a toggle added in the config that I can enable to disable the fan direction characteristic all together. The goal is to remove the fan direction option on this device in HomeKit.

**Comment by oogje** [comment]
I'd like to provide a config to remove the direction control altogether but failing that it should be straightforward to have it just ignore the control.

**Comment by bschuchert** [comment]
Perfect. Yeah, ideal state would be to not have the control there at all. Ignoring change events would be a good backup plan to avoid inadvertent taps. Thanks.

**Comment by oogje** [comment]
My pleasure.  I've published `homebridge-i6-bigassfans@0.5.2-beta1` which pretty much ignores the direction control because I haven't found out how to remove it altogether.  Since the control is still present one can see if the direction is changed by the BAF app or a remote.

The config attribute would be `"disableDirectionControl": true`

The control still responds if you press it but it won't change the direction and will revert to the actual direction when the fan reports.  I could probably force the control back immediately if someone changes it but then I'd rather ignore it than fight with it, if that feels okay in practice.

**Comment by bschuchert** [comment]
I just installed and tested it. So far, so good. I'll let you know if I find anything weird. Thanks again.

**Comment by oogje** [comment]
Great.  Thanks for testing.

**Comment by oogje** [comment]
I haven't had any luck finding a way to remove the direction control entirely, so I'm going to pronounce this done until or unless I come across a better solution.
